AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Bucket and EC2 instance using Mapping.

Mappings:
  InstanceSize:
    SMALL:
      "Mac1" : "t2.micro"
      "Mac2" : "t2.micro"
    MEDIUM:
      "Mac1" : "t2.medium"
      "Mac2" : "t2.medium"
    LARGE:
      "Mac1" : "t2.large"
      "Mac2" : "t2.large"

Resources:
  MyEC21:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                                     # Replace with your Amazon Linux AMI ID
      InstanceType: !FindInMap [InstanceSize, SMALL, Mac1]
  MyEC22:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                                     # Replace with your Amazon Linux AMI ID
      InstanceType: !FindInMap [InstanceSize, SMALL, Mac2]
  MyS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: iacc-xxxxxxxxxxx                              # Replace xxxxxx with your full name.